### ISSUE TITLE
How can I run a test in jqwik?

### ISSUE THREAD

**Issue by igorcmoraes** [jlink/jqwik#105]
Sorry guys, I'm a noob in programming languages. So, there's the most shameful question:

How can I run tests with this library? I usually do my tests with JUnit, with eclipse, and I just need to write my test cases and click in Run As -> JUnit.

For jqwik, I created a project maven, then I added the jqwik and assertj dependencies on pom.xml
After that I created a package "testes" in the test folder, and a class with this example:

```
package testes;

import net.jqwik.api.*;
import org.assertj.core.api.*;

class PropertyBasedTests {
		@Property
		boolean absoluteValueOfAllNumbersIsPositive(@ForAll int anInteger) {
			return Math.abs(anInteger) >= 0;
		}
		@Property
		void lengthOfConcatenatedStringIsGreaterThanLengthOfEach(@ForAll String string1, @ForAll String string2) {
			String conc = string1 + string2;
			Assertions.assertThat(conc.length()).isGreaterThan(string1.length());
			Assertions.assertThat(conc.length()).isGreaterThan(string2.length());
		}
}
```

How can I run this? Sorry for the stupid question, but I don't know who to turn to.
Thanks!

**Comment by luvarqpp** [comment]
Hi,
I have personally used eclipse a bit long time ago, but it seems that in context menu you should have desired functionality. Have a look at http://www.eclipseonetips.com/2014/06/16/run-a-single-junit-test-method-in-eclipse/

If maven configuration is picked-up correctly by eclipse, it should have no problem running jqwik engine instead of junit-jupiter.

Another possibility is to use command line and execute `mvn test` for starting all tests, or use `mvn -Dtest=TestCircle test` to execute single test. Use your favorite search engine for more tips.

PS: I would you to use [stack overflow](https://stackoverflow.com/questions/tagged/jqwik) for questions like this.

**Comment by jlink** [comment]
@igorcmoraes The short answer is: It works exactly like JUnit (5) given that your Maven project is correct. Have a look at https://github.com/jlink/jqwik-samples/tree/master/jqwik-starter-maven to see the minimal Maven file.

**Comment by jlink** [comment]
I update the user-guide section to point to the starter example: https://jqwik.net/docs/current/user-guide.html#maven

I hereby close the issue. If you have more questions on how to run (or use) jqwik I also recommend to do that on [stack overflow](https://stackoverflow.com/questions/tagged/jqwik)
