### ISSUE TITLE
Builders with many parameters fail since 1.3.0

### ISSUE THREAD

**Issue by jdmarble** [jlink/jqwik#113]
## Testing Problem

Since version 1.3.0, some of my tests started running out of heap space. They all involve builders with many parameters. [Here](https://gist.github.com/jdmarble/df0c0db22dfcd40921fdbd0a1b7bb864) is a minimal test case that blows the default heap size on my machine.

## Suggested Solution

I'm guessing this has to do with the new edge case logic. Perhaps all of the edge cases in a complex builder are compounding exponentially. Would it be a good idea to fall back to the old behavior in pathological cases like this?

## Discussion

All combinations of edge cases in large builders is a big search space. I don't expect that to be covered. I do like having confidence that each of the individual fields has had the edge cases tested in isolation. Then, sampling of the full search space is a bonus!

**Comment by jlink** [comment]
@jdmarble Thanks for the catch.
In theory the high combinatorics _shouldn't_ matter because edge case suppliers _should_ only be evaluated when requesting the next edge case. Practice is obviously different though...

I'll have a closer look later. What you can do in the meantime is switch edge cases off.
Either per property:

```
@Property(edgeCases = EdgeCasesMode.NONE)
public void my_property(@ForAll("things") final Thing thing) {
	// No longer runs out of heap before getting here.
}
```

or globally in the jqwik configuration file: https://jqwik.net/docs/current/user-guide.html#jqwik-configuration

**Comment by jlink** [comment]
OK. I had a look. Bad news :-( At least for the time being.

Looks like I switched from just streaming edge cases on the fly to collecting them beforehand sometime during implementation. I'm sure there was a reason for it that I currently cannot remember. 

That's why I opened a new feature issue: https://github.com/jlink/jqwik/issues/114

That means that I'll not tackle it at once but as soon as it's high enough in jqwik's overall todo list.

**Comment by jlink** [comment]
Hope the workaround is ok until the feature will be tackled.

**Comment by jdmarble** [comment]
Thanks for looking into it! The workaround is working for me.

**Comment by jlink** [comment]
As of 1.3.5 generating edge cases will be stopped after 10000 generated values.
