### ISSUE TITLE
Generating unique values

### ISSUE THREAD

**Issue by tmohme** [jlink/jqwik#143]
## Testing Problem

I'd like to generate values that are unique within all tries of a property.
The UserGuide makes it clear that `@Unique` provides not strong enough guarantees for this.
Nevertheless, the API function `net.jqwik.api.Arbitrary#unique` seems to do exactly what I need (according to its doc):

> Create a new arbitrary of the same type {@code T} that creates and shrinks the original arbitrary but will
> never generate the same value twice.
>
> <p>
>     Uniqueness is only held up for a single use of this arbitrary.
>     If the same arbitrary instance is used in several places,
>     e.g. for creating several lists, the different lists may share values
>     between them.
> </p>

But when I use this function (v1.3.10), the produced Arbitrary still produces duplicate values (over several tries) within one property, which is obviously not what _I_ expected.
Maybe it's just that I don't really get the second paragraph . . .

## Suggested Solution

It would be great to have the option to let an arbitrary generate unique values over all the tries of a property.

## Discussion

I have tried to understand what is happening "under the hoods" to deduce what I might have done wrong.
My current limited understanding is that I probably misunderstood the second paragraph of the API doc and the function is not supposed to what I expected. 
If that is the case, then maybe the API doc could be clearer: What exactly is "a single use of this arbitrary" - I'm using the arbitrary only once.

Kotlin Reproducer:
```
class Reproducer {
    private val generated = mutableSetOf<String>()

    @Report(Reporting.GENERATED)
    @Property
    fun reproduce(@ForAll("unique") s: String) {
        require(!generated.contains(s))
        generated += s
    }

    @Provide
    fun unique(): Arbitrary<String> =
            Arbitraries
                    .strings()
                    .ofMinLength(1)
                    .ofMaxLength(8)
                    .numeric()
                    .unique()
}
```

**Comment by jlink** [comment]
To be frank, `Arbitrary.unique()` as it is now is a broken concept. I've fought with it quite a while and tried to make it sound but there are some aspects which prevent that. That's why it will be deprecated in 1.4.0 (the upcoming version, due probably early 2021). It will be replaced by something else to cover the most common scenarios I know of.

That being said, the feature that you want, uniqueness _across_ different tries will not be covered. The crucial point is that PBT (as I understand it) is not about constraints across all tries. If you had that, it would not be able to reuse a unique object while shrinking; and shrinking requires that calling a property with the exact same values will reproduce the exact same result.

Maybe I can understand your use case better to come up with a suggestion of how to tackle it. My guess is that you don't really want uniqueness across tries ;-) Can you write a bit more about what you want to achieve with the property?

**Comment by tmohme** [comment]
You have a valid point in saying that PBT is not about constraints across all tries.

I'm doing some kind of acceptance tests of a system that persists data.
The clean solution would obviously be, to ensure a *fully* defined state before each try, but that is time-consuming.
So I though, maybe I can get away cheaper when I only do the full initialization for each property and within the tries of a property just ensure I use unique keys.

All in all it is just _one_ form of an optimization, so it is by no means a deal-breaker.
As a first workaround, I'll probably build the uniqueness with a set and `Assert.that()` by myself.

Nevertheless maybe a short update of the API doc would be appropriate.

**Comment by jlink** [comment]
> In this particular case I might even go with @Example instead of @Property because all the actual testing is done on the unit-level.

You may want to use [data-driven properties](https://jqwik.net/docs/current/user-guide.html#data-driven-properties) and hand in a few hand-made unique ids.

> Nevertheless maybe a short update of the API doc would be appropriate.

It will be completely reworked with the new concept.

**Comment by jlink** [comment]
Feel free to reopen if you think any work is necessary BEFORE introducing the reworked unique mechanism.

**Comment by jlink** [comment]
@tmohme I've just thought of a solution for your problem. You can combine data driven properties with arbitraries like that:

```java
class Reproducer {

	private List<String> generated = new ArrayList<>();

	@Property
	@FromData("uniqueIDs")
	@Report(Reporting.GENERATED)
	void reproduce(@ForAll("unique") String s) {
		Assertions.assertThat(generated).doesNotContain(s);
		generated.add(s);
	}

	@Data
	Iterable<Tuple.Tuple1<String>> uniqueIDs() {
		Arbitrary<Tuple.Tuple1<String>> ids = unique().tuple1();
		return ids.sampleStream().limit(100).collect(Collectors.toList());
	}

	@Provide
	Arbitrary<String> unique() {
		return Arbitraries
			.strings()
			.ofMinLength(1)
			.ofMaxLength(8)
			.numeric()
			.unique();
	}
}
```

Since uniqueIDs() is using Arbitrary.sampleStream() the unique constraint holds for all generated IDs.

Sorry for using Java. I was too lazy to set up a Kotlin project right now.

**Comment by tmohme** [comment]
@jlink Thank you for your suggestion.
Initially I was a bit confused about the @ForAll value parameter and the @Provide annotation but I guess the example is just not "polished".

**Comment by jlink** [comment]
@tmohme I was in a hasty mood.
