### ISSUE TITLE
Uniqueness for arbitrary Strings

### ISSUE THREAD

**Issue by talios** [jlink/jqwik#169]
## Testing Problem

Prior to the recent release of 1.5.0, I had the following arbitrary pattern for providing "invalid passwords"

```java
Arbitraries.strings()
  .withChars(VALID_CHARACTERS)
  .ofMinLength(1)
  .ofMaxLength(PASSWORD_MIN_LENGTH - 1)
  .unique()
  .map(Password::of);
```

Which the removal of `.unique()` I'm left wondering how to handle this.

The desire to not retry/provide the same password twice in a given test.

## Suggested Solution

...unknown...

**Comment by jlink** [comment]
@talios Thanks for bringing that up. I obviously did not communicate the idea behind uniqueness in a sufficiently clear manner. That's true for both the old and the new approach.

Your question does - I assume - derive from a wrong assumption about what the "old" (<= 1.3.10) uniqueness did. Let's look at an example:

```java
	private static final String VALID_CHARACTERS = "abc1243";
	private static final int PASSWORD_MIN_LENGTH = 5;

	@Property(tries = 100)
	void generatedPasswordsAreNotUnique(@ForAll("passwords") Password aPassword) {
		System.out.println(aPassword);
	}

	@Provide
	private Arbitrary<Password> passwords() {
		return Arbitraries.strings()
						  .withChars(VALID_CHARACTERS)
						  .ofMinLength(1)
						  .ofMaxLength(PASSWORD_MIN_LENGTH - 1)
						  .unique()
						  .map(Password::of);
	}
```

You  might expect that the generated passwords are unique across all tries, i.e. for the whole property.
That's not true, however, which you can see when you look at the generated passwords in the property above.
If you haven't seen duplicate passwords so far, the reason for that is probably that they are too rare when the set of allowed characters is big enough. For further discussion you may want to look at this issue: https://github.com/jlink/jqwik/issues/143

The real uniqueness comes into play when you generate collections, e.g. lists or sets, of values. Here with the old approach:

```java
@Property(tries = 10)
void listOfPasswordsIsUniqueOld(@ForAll("listOfPasswordsOld") List<Password> passwords) {
	Set<String> setOfPasswords = passwords.stream().map(p -> p.password).collect(Collectors.toSet());
	Assertions.assertThat(setOfPasswords).hasSameSizeAs(passwords);
}

@Provide
Arbitrary<List<Password>> listOfPasswordsOld() {
	return passwords().list().ofMinSize(1).ofMaxSize(100);
}

@Provide
private Arbitrary<Password> passwords() {
	return Arbitraries.strings()
					  .withChars(VALID_CHARACTERS)
					  .ofMinLength(1)
					  .ofMaxLength(PASSWORD_MIN_LENGTH - 1)
					  .unique()
					  .map(Password::of);
}
```

This can be easily translated into the new approach:

```java
@Property(tries = 10)
void listOfPasswordsIsUniqueNew(@ForAll("listOfPasswords2") List<Password> passwords) {
	Set<String> setOfPasswords = passwords.stream().map(p -> p.password).collect(Collectors.toSet());
	Assertions.assertThat(setOfPasswords).hasSameSizeAs(passwords);
}

@Provide
Arbitrary<List<Password>> listOfPasswordsNew() {
	return Arbitraries.strings()
					  .withChars(VALID_CHARACTERS)
					  .ofMinLength(1)
					  .ofMaxLength(PASSWORD_MIN_LENGTH - 1)
					  .map(Password::of)
					  .list().uniqueElements().ofMinSize(1).ofMaxSize(100);
}
```

The new approach is even more flexible because you do not have to rely on an object's equality but can use a function to define your uniqueness criterion: https://jqwik.net/docs/current/user-guide.html#uniqueness-constraints

I hope this could clarify some of the confusion.

**Comment by talios** [comment]
+200 Thanks for the awesome explanation there - ended up just dropping `.unique()` and that's all I needed.
