### ISSUE TITLE
OOM happens when using combinator to build arbitrary with filter

### ISSUE THREAD

**Issue by seongahjo** [jlink/jqwik#200]
## Testing Problem
Since 1.5.0 version, when I use combinator to build object with filter,  OOM is happened

It works well in 1.3.10 version.

You can regenerate this issue, check this [repository](https://github.com/seongahjo/test-jqwik-memory-leak)

![image](https://user-images.githubusercontent.com/10272119/123601801-1019f380-d833-11eb-9fcf-4301a2f203ad.png)

## Suggested Solution

I don't know exact causes :X

**Comment by jlink** [comment]
Thanks for reporting. I'll have a look at it.

**Comment by jlink** [comment]
Just to check: Have you tried 1.5.1 or 1.5.2 because 1.5.1 fixed a memory leak: https://jqwik.net/release-notes.html#151

**Comment by seongahjo** [comment]
@jlink 
yes, I have tried 1.4.0, 1.5.0, 1.5.1, 1.5.2
only 1.4.0 works well

**Comment by seongahjo** [comment]
@jlink 
may be the reason why OOM happens is
`arbitrary.generatorWithEmbeddedEdgeCases(genSize).withEdgeCases(genSize, arbitrary.edgeCases(maxEdgeCases))`

when I changed it to `arbitrary.generator(genSize).withEdgeCases(genSize, arbitrary.edgeCases(maxEdgeCases))`, it works well.

**Comment by jlink** [comment]
Not  being on a valid computer I could not try out your example but I had a look at the test.  Can you say something about the purpose of the test? 

The reason I’d like to know is that you’re doing a few unusual things in there, like sampling and creating arbitraries, which are not supposed to be used inside a property method. Jqwik‘s caching policy, which is most probably responsible for the OOM, has been designed for use inside the standard lifecycle, ie building arbitraries only in providers and provider methods. So I’m quite confident the goal of your test can be reached without „non-standard“ usage. 

That said, I’ll still try to figure out the reason for the OOM and fix it if possible.

**Comment by jlink** [comment]
Following up on my comments from above, one small change to the test fixes the OOM for me:

```java
@Property
void test_original() {
	BuilderCombinator<IntegerListBuilderClass> builderCombinator =
		Combinators.withBuilder(IntegerListBuilderClass::new);

	int random = Arbitraries.integers().between(0, 5).sample();
	for (int i = 0; i < random; i++) {
		IntegerArbitrary integer = Arbitraries.integers();
		builderCombinator = builderCombinator.use(integer).in(IntegerListBuilderClass::add);
	}
	builderCombinator.build(IntegerListBuilderClass::build)
		.filter(it -> it.size() == random)
		.sample();
}

@Property
// Let jqwik generate the random value for you
void test_modified(@ForAll @IntRange(min = 0, max = 5) int random) {
	BuilderCombinator<IntegerListBuilderClass> builderCombinator =
		Combinators.withBuilder(IntegerListBuilderClass::new);

	for (int i = 0; i < random; i++) {
		IntegerArbitrary integer = Arbitraries.integers();
		builderCombinator = builderCombinator.use(integer).in(IntegerListBuilderClass::add);
	}
	builderCombinator.build(IntegerListBuilderClass::build)
		.filter(it -> it.size() == random)
		.sample();
}
```

Why did the behaviour change in version 1.4? The history is similar to that:
- 1.4 changed the way how edge cases are being generated
- This led to heavy performance penalties in some combinators and flat-mapping scenarios
- To fix this (through memoizing of generator creation) I had to make an incompatible change -> 1.5.0
- But there was a memory leak in the original memoizing code -> 1.5.1
- Memoizing, however, requires to store both the arguments of a function and the result, which eats memory

This is usually not a problem in most scenarios, unless very many generators are being created in a single property run. 
This happens in your code. Each call to `sample()` will create a new generator (actually most calls will); times 1000; times random; you get the idea... 
`sample()` is considered to be used sparingly, if at all. Mostly to experiment with arbitraries or to use an arbitrary outside of jqwik properties, eg in a JUnit Jupiter test in order to create test data.

If you write more about the real scenario in which you hit the OOM, we can probably come up with a more jqwikish way to do it; maybe `test_modified` already suffices.

BTW, the fix you suggest in `ArbitraryFacadeImpl` would break current edge cases generation behaviour.

**Comment by seongahjo** [comment]
Thank you for the reply.
I understand why OOM happens, I think I can avoid it.

I'm currently use sample for testing objects made by Jqwik.
I think I'd better to write test test jqwikish way like you said.

**Comment by jlink** [comment]
My recommendation when using jqwik generators outside of jqwik properties: Use `sample()` in one place only. To combine several arbitraries use what jqwik offers: map, filter, flatMap, combine, flat combine and builders.

I'll close this issue for now. Feel free to reopen it if you need more assistance.
