### ISSUE TITLE
CalendarArbitrary is not support Time

### ISSUE THREAD

**Issue by mhyeon-lee** [jlink/jqwik#299]
## Discussion

CalendarArbitrary is all about date information. (using LocalDateArbitrary)

Any plans to handle time information?

**Comment by jlink** [comment]
There's already an open issue for that: https://github.com/jlink/jqwik/issues/228

However, it's not on my current timeline because:
1. Many/most people nowadays use the types in `java.time`
2. There's an easy workaround: Generate `Instant`, `LocalDateTime` or whatever and map it to `Calendar`, e.g.

  ```java
	@Property(tries = 10)
	void calendarsFromInstants(@ForAll("calendars") Calendar cal) {
		System.out.println(cal.getTime());
	}

	@Provide
	Arbitrary<Calendar> calendars() {
		return DateTimes.instants().map(instant -> {
			ZonedDateTime zdt = ZonedDateTime.ofInstant(instant, ZoneId.systemDefault());
			return GregorianCalendar.from(zdt);
		});
	}
  ```

Hope that helps.
