### ISSUE TITLE
LazyArbitrary does not delegate Arbitrary#edgeCases

### ISSUE THREAD

**Issue by vlsi** [jlink/jqwik#301]
Is there a reason `LazyArbitrary` not delegating `edgeCases`?

I have no particular use case, however, it looks like delegating `edgeCases` should be ok

**Comment by jlink** [comment]
The problem is recursion. `Arbitraries.lazy()` is explicitly made to support probabilistic recursion as described here: https://jqwik.net/docs/current/user-guide.html#recursive-arbitraries.

Edge cases generation requires a fully expanded generator hierarchy. Expanding a recursive arbitrary will never end, though, and lead to a stack overflow.

Interestingly, exhaustive generation does not suffer from that problem, because the algorithm is able to detect recursive calls and break off.
