### ISSUE TITLE
Question about `Combinators.flatAs` performance 

### ISSUE THREAD

**Issue by chriskiehl** [jlink/jqwik#383]
## Testing Problem

Hey there! 

I'm encountering a few performance issues with Jqwik. I want to check if my usage of the framework is inline with what's expected, or if I'm "holding it wrong" and inadvertently shooting myself in the foot. 

In short, I'm seeing an issue where `Combinator.flatAs` is about 10x slower than building the same object from independently created arbitraries. 

As a concrete example, I want to generate an object via `Arbitraries.forType`, as well as apply a few customization to some of its generated fields. Currently, I'm doing that via `flatAs` off of the Combinator like this: 

```
@Builder 
class MyObject {
    BigDecimal a; 
    LocalDate b; 
    .... 
    String z; 
}

arbitraryMyObject = Combinators.combine(someArbitraryA(), someArbitraryB())
    .flatAs((a, b) -> 
        Arbitraries.forType(MyObject.class).useAllConstructors().map(myObject -> 
            myObject.builder().a(a).b(b).build();  
```

This generally works. However, the performance of this is fairly bad. It takes about 10 seconds to generate a list of 1k entries. 

```
long start = System.currentTimeMillis()
arbitraryMyObject.list().ofSize(1000).sample(); 
System.currentTimeMillis() - start 
// about 10s 
```

**Some experiments in mitigating the performance issue:**

**Approach #1:** generating the two arbitraries (the object and its customizations) independently, sampling each, and then merging them into one final object. 

```
customizations = Combinators.combine(someArbitraryA(), someArbitraryB()).as(Tuple::of).list().ofSize(1000).sample(); 
objects = Arbitraries.forType(MyObject.class).useAllConstructors().list().ofSize(1000).sample(); 
// Using Vavr's API for brevity here
objects.zipWith(customizations, (tuple, myObject) -> myObject.builder().a(tuple._1).b(tuple._2).build());
```

This is the fastest option I've found clocking in a sub 1s for generating both sets of 1k items and stitching them together. The downside is that I have to 'leave' the Arbitrary and sample in order to get that speed. 

**Approach #2:** generating the two arbitraties independently and then manually `flatMap`ping them together. 

```
customizations = Combinators.combine(someArbitraryA(), someArbitraryB()).as(Tuple::of)
objects = Arbitraries.forType(MyObject.class).useAllConstructors()

myArbitraryObject = objects.flatMap(myObject -> customizations.map(
    tuple -> myObject.builder().a(tuple._1).b(tuple._2).build())


// benchmarking how long to create 1k 
myArbtiraryObject.list().ofSize(1000).sample(); 
```

This one is slower that the first option, but still about 10x faster than going straight off the Combinator. It clocks in around 1s on my machine. 

**Questions:**

* Why is `flatAs` so much slower than the alternatives? 
* Should I be building objects differently to avoid performance hits? 
* Are the presented options valid work-arounds when encountering performance woes, or are there better methods / approaches?

**Comment by vlsi** [comment]
Which jqwik version do you use?
Have you tried building the recent one from sources?
Could you try profiling the execution (e.g. via Java Flight Recorde)?

**Comment by jlink** [comment]
I won’t be able to really try out a few options before next week. Therefore, just some general remarks: flat mapping can get (very) slow because generating edge cases is combinatorical. In simple cases you won’t notice but when using nested flat mapping this can get bad. Builders use some kind of flat mapping under the hood, so this might be what’s happening here. 
Have you tried switching off edge cases?

In general, I try to avoid flat mapping when I see equivalent approaches, since flat mapping also comes with worse shrinking performance that most other generators. 

I like your alternative 1. Another idea: Use a domain to register your modifying arbitraries, and then go for a plain ˋArbitraries.forType(..)ˋ.

**Comment by jlink** [comment]
@chriskiehl Any news here? 

If this issue is still of interest to you, there's another important question: Are you using the resulting objects in properties or for other testing purposes? If the former, you should never call `sample()` explicitly as in your approach #1.

What you are trying to do looks like a use case for https://jqwik.net/docs/current/user-guide.html#combining-arbitraries-with-builders to me. Especially since I assume that `myObject.builder()` would not use the state of `myObject` at all, so generating it makes no sense. At least if it is the Lombok `@Builder` annotation you are dealing with here.

To sketch it out (I haven't compiled it):

```java
Builders.withBuilder(() -> MyObject.builder())
							  .use(someArbitraryA()).in((builder, a) -> builder.a(a))
							  .use(someArbitraryB()).in((builder, b) -> builder.b(b))
							  .build( builder -> builder.build());
```

Could that work? If it does, I'd assume the performance to be significantly better.

**Comment by jlink** [comment]
Closing. Feel free to reopen if the tips above don't solve the problem.

**Comment by chriskiehl** [comment]
>Any news here? 

Hey -- sorry, just to follow up, I didn't do much additional experimentation after opening the issue. Deadlines loom every present, so we ended up offloading a lot of the data creation to EasyRandom. We still use Jqwik for generating seeds and other straight forward values that are passed directly as part of the property definition (`@Forall ...`). The combination is working pretty well. We give up a few features like shrinking, but, that's not a huge loss for our use cases, as, due the complexity of the objects, shrinking was more-or-less guaranteed to be unsuccessful. 

>Are you using the resulting objects in properties or for other testing purposes? 

A good mix of both : )  

Thanks for the builder suggestion. I'll have to play around with it (I can report back once I've dug in a bit). 

Cheers!
