### ISSUE TITLE
Edge cases added via `Arbitrary#edgeCases(Consumer<EdgeCases.Config<T>>)` aren't ever provided

### ISSUE THREAD

**Issue by BenWhitehead** [jlink/jqwik#384]
## Testing Problem

I'm attempting to leverage [Configuring Edge Cases Themselves](https://jqwik.net/docs/current/user-guide.html#configuring-edge-cases-themselves) to explicitly define some edgecases for some parsing code I'm writing. However, the issues I'm running into, is my `@Property` methods never receive the edge case values.

I've tried with both generative arbitraries (`Arbitraries.integers().between(10, 30).injectNull(0.25).edgeCases(a -> a.add(9, 31))`, and explicitly defined ones (`Arbitraries.of("ENUM_1", "ENUM_2").injectNull(0.25).edgeCases(a -> a.add(""))`). But I've been unsuccessful getting things to work.

Here is a gist with a minimized repro of the issue I'm seeing for both cases, along with the output from running the tests.
https://gist.github.com/BenWhitehead/cec67f02e078c00bad67e90f8b6dc9de

I imagine, I'm doing something wrong but I'm not sure what.

Thank you in advance for your help!

### Environment
jqwick version: `1.6.5`
java version: `1.8.0_292`

## Suggested Solution

No specific solution in mind

**Comment by jlink** [comment]
The behaviour you observe works as designed. Have a look at the Javadoc for `EdgeCases.add(..)`:

```java
/**
 * Add one or more unshrinkable additional values as edge cases.
 *
 * <p>
 * Some arbitraries may allow those values to be outside the value range generated by this arbitrary;
 * this is mainly due to implementation issues.
 * In general you should not add "forbidden" values since it will weaken the semantics
 * of built-in constraints.
 * </p>
 *
 * @param edgeCases The edge cases to add to default edge cases.
 * @return same configuration instance
 */
@SuppressWarnings("unchecked")
Config<T> add(T... edgeCases);
```

In your two examples, the edge cases you add are outside the generation domain of the arbitrary you add them to.
An edge cases (in jqwik's dictionary) is a value that could be generated by an arbitrary but may not be through pseudo-random generation, because it is, well, random. jqwik makes sure that edge cases - and combinations of them - will be generated early with a high probability or, when you use `@Property(edgeCases = EdgeCasesMode.FIRST)` before any randomly generated values.

It looks like what you want to do in your examples is to add special cases that are outside the original range:

```java
Arbitraries.oneOf(
  Arbitraries.integers().between(10, 30).injectNull(0.25),
  Arbitraries.of(9, 31)
)
```

With 9 and 31, however, your intention might already be covered by `Arbitraries.integers().between(9, 31).injectNull(0.25)`, since jqwik is already using the borders of a number range as edge cases.

If you _really_ wanted to add special values _and_ mark them as edge cases, you'd have to do it like that:
```java
@Provide
Arbitrary<Integer> anyInteger() {
  return Arbitraries.oneOf(
    Arbitraries.integers().between(10, 30).injectNull(0.25),
    Arbitraries.of(9, 31)
  ).edgeCases(
    a -> a.add(9, 31)
  );
}
```
but I doubt that this is worth the effort in most cases.

What your question shows is that documentation is lacking clarity here. What information was missing and where in the documentation was it missing?

**Comment by BenWhitehead** [comment]
Thank you so much for clarifying for me!

I guess where I stumbled, is in [Configuring Edge Cases Themselves](https://jqwik.net/docs/current/user-guide.html#configuring-edge-cases-themselves) it states
> Here’s an example that shows how to add a few “special” strings to a generator

I read that to mean the edge cases added via the `.add(T)` method would be added to the arbitraries domain. Whereas if I'm understanding your response correctly, edge case values are themselves from within the defined domain and are instead denoted as edge cases.

I will probably end up following your third example, as I do want the edge case info to carry through to those larger/deeper objects composed of multiple arbitraries. Having combined edge cases has been really valuable for our usage and I want to carry that through.

As for what clarification could be made in the docs: I think stating that when adding/filtering edge cases the specified value(s) should intersect with the generators existing domain.

**Comment by jlink** [comment]
@BenWhitehead Thanks for the feedback. I'll (try to) improve the documentation.

**Comment by BenWhitehead** [comment]
Thanks! Feel free to close this issue if it isn't useful for your workflow. Having the explanation here is a great fallback for any interim time frame.

**Comment by jlink** [comment]
Hopefully clarified edge cases configuration in https://github.com/jlink/jqwik/commit/e75a22eda99d20160eaec2c60e0e44afbfd8ccec

**Comment by jlink** [comment]
See https://jqwik.net/docs/snapshot/user-guide.html#configuring-edge-cases-themselves

**Comment by BenWhitehead** [comment]
That looks great @jlink! Thanks so much for the new explanation and code sample!
