### ISSUE TITLE
Dealing with constraints on collection/array types

### ISSUE THREAD

**Issue by adam-waldenberg** [jlink/jqwik#399]
## Testing Problem

Specifying `@ForAll @AlphaChars String[] strings` in a method silently does nothing at the moment. I am aware that I can create a provider for a custom String[] to achieve the same thing - however it seems like a shame that JQwik cannot infer what to do by simply looking at the type of the collection or array. Rather than doing nothing, falling back to the type of the collection/array would be very useful.

## Suggested Solution

1. First and foremost, apply the constraint on the containing type (collection/array) if possible.
2. If that isn't possible, infer what to do based on the type inside the collection or array.
3. If not 2, (less preferable) throw an exception, informing the user the specific constraint does nothing on the provided type. ´@AlphaChars´ makes no sense on an array for example- even if it might make sense on the type inside the array.

## Discussion

If an action can't even be infered based on the collection/list or contained type and the constraint doesnt work on any of them - an exception should probably be thrown rather than failing silently.

## Current Workaround

Currently I'm doing the following to get the same end result:

```java
@Provide
public Arbitrary<String[]> alphaCharsArray() {
	return Arbitraries.strings().alpha().array(String[].class);
}

@Property
public void shouldSomethingSomething(@ForAll("alphaCharsArray") String[] strings) {
	...
}
```

**Comment by jlink** [comment]
Thanks for asking. 

You are touching two points here:

1. Applying constraint annotations to an array’s component type: The behaviour you suggest is how jqwik worked until 1.6.1. See https://jqwik.net/docs/1.6.2/user-guide.html#constraining-array-types for a short explanation why it was changed.

2. Finding out if a constraint property is applicable or not and alerting the user if the constraint does not make sense: Sadly, this cannot be solved with the current design of how constraints work.  They are based on the idea of arbitrary configurators, any number of which can be registered by jqwik itself, an extension or the testing developer themselves. That means, that even if the default configurators for ˋ@AlphaCharsˋ cannot deal with ˋString[]ˋ, another configurator could. To find out if at least one configurator felt responsible, jqwik would have to collect and remember this info, which it currently doesn’t. 

Due to the second point, I’ll have to reject your suggestion - at least until a major design change will allow it. But that also provides a possibility for you to make those annotations work that are important to you: Just register a configurator for type ˋString[]ˋ and annotation ˋ@AlphaCharsˋ. The following section from the userguide might be helpful: https://jqwik.net/docs/1.7.0/user-guide.html#create-your-own-annotations-for-arbitrary-configuration

**Comment by jlink** [comment]
Feel free to ask if you need more guidance about self-made configurators.
