### ISSUE TITLE
Combinator with more than eight arbitraries

### ISSUE THREAD

**Issue by jpotecki** [jlink/jqwik#40]
## Creation of a combinator with more than eight arbitraries

In the doc it says, that I should create an issue, once I need more than eight arbitraries, so here I am :)
Unfortunately all those arbitraries have different types, so I cannot use `Combinators.ListCombinator<T> ` as input. 
An hacky way to create Objects with more than 8 fields might be to use the `@interface` and then pass those to each `@ForAll` but that would also make the tests pretty unreadable.

Is there another way to do that right now? Maybe how to create a provider with any amount of arbitraries?

Cheers,
Janos

**Comment by jlink** [comment]
I have two answers for you, a simple one and a right one.

## Simple Answer

You can always combine arbitraries in several steps, e.g.

```
@Provide
Arbitrary<Customer> aCustomer() {
    Arbitrary<String> street1 = ...;
    Arbitrary<String> zip1 = ...;
    Arbitrary<String> city1 = ...;
    Arbitrary<String> street2 = ...;
    Arbitrary<String> zip2 = ...;
    Arbitrary<String> city2 = ...;
    Arbitrary<Tuple3> address1 = 
            Combinators.combine(street1, zip1, city1).as((s, z, c) -> Tuple.of(s, z, c);
    Arbitrary<Tuple3> address2 = 
            Combinators.combine(street2, zip2, city2).as((s, z, c) -> Tuple.of(s, z, c);
    return Combinators.combine(address1, address2)
            .as( (t1, t2) -> new  Customer(t1.get1(), t1.get2(), ... t2.get3());
}
```

I haven compiled the code but you get the idea.

## Right Answer

With so many individual parts there are most certainly domain concepts hidden somewhere. Those domain concepts should be domain classes and then get their own arbitrary providers. In this case there's an Address class looming and having that in place I'd probably write an AddressArbitraryProvider and register it, so that I can generate arbitraries for it without any further effort.

Maybe if you post your concrete code, we can look for a good approach together.

**Comment by jpotecki** [comment]
Hi, 
thanks for the provided information. Indeed `Tuple3` would solve my issue. 
Regarding the `Right Answer`:
Let us stick to the case, where we want to create a `Customer`
I understand that creating a AddressArbitraryProvider` and e.g. a `BirthdayInformationArbitratryProvider` would be the preferred way to handle these cases. It would be nice to be able to combine these providers if necessary.

**Comment by jlink** [comment]
So you want to combine arbitraries that are already handled by registered arbitrary providers?
You can do this:

```
@Provide
Arbitrary<Customer> aCustomer() {
    Arbitrary<Address> address = Arbitraries.defaultFor(Address.class);
    Arbitrary<Birthday> birthday = Arbitraries.defaultFor(Birthday.class);
    return Combinators.combine(address, birthday).as(a, b -> new Customer(a, b));
}
```

**Comment by jlink** [comment]
I'd like to close the issue. Any more problems with that or further questions?
