### ISSUE TITLE
Why the need for @ForAll

### ISSUE THREAD

**Issue by Sir4ur0n** [jlink/jqwik#43]
Surprisingly I could not find any issue that tracks this need, while the documentation states:

> Currently jqwik cannot deal with parameters that are not annotated with ‘@ForAll’. However, this might change in future versions.

I think this is verbose to put `@ForAll` on every single parameter, and I think we all agree that it's the default need for everyone to inject random parameters.

Is it a technical limitation?

**Comment by Sir4ur0n** [comment]
I don't think the intent is that much of a deal. When one wrote `@Property` I think it's quite explicit they're trying to write a property holding for all inputs, it's the default for property tests.
Since it's probably the 80% or the 95% of use cases, I'd rather make it implicit and by default, and instead have an annotation to disable automatic injection for the 5% or 20%. Ideally, a meta annotation so that it can be put on another annotation for special use cases (e.g. I'm creating a `@AlwaysReuseTheSame` annotation, that I can annotate with `@DisableInjection` provided by Jqwik, so that when a parameter has `@AlwaysReuseTheSame` annotation in a property, Jqwik backs off and lets any other extension mechanism take care of it (of course, throw as usual if no extension mechanism took care of it)).

Besides verbosity, I don't see any major disadvantage to keeping `@ForAll` explicit. But verbosity (or absence thereof) is a major feature in library choice. And everything that makes tests easier to read/write is IMHO a step in the right direction. And Java is already verbose enough 😄

**Comment by pholser** [comment]
When I started junit-quickcheck, the way you wrote property-based tests with it was to use the `Theories` runner and mark the randomized parameters with the annotation `@ForAll`. This was to leverage the `ParameterSupplier` capability of the `Theories` runner -- that is how the runner was told what values to invoke your PBT with. When junit-quickcheck began supplying its own runner (`JUnitQuickcheck`), the need for `@ForAll` sort of fell away -- the runner scraped `@Property` methods from the test class and ran those.

There's a certain appeal to `@ForAll` in how a PBT reads with it:

    @Property void symmetric(@ForAll Thing a, @ForAll Thing b) {
        // ...
    }

highlighting the intended universality of the test -- for any two `Things` you give me, such-and-such property holds.

Also, because `@Forall`'s `value attribute allows reference to provider methods, the readability aspect becomes even stronger:

    @Property void symmetric(@ForAll("speciallyCrafted") Thing a, @ForAll Thing b) {
        // ...
    }

All that said, I'd be OK with making `@ForAll` optional, and if the need arises to suppress parameter injection address it another way.

**Comment by jlink** [comment]
The case for making `@ForAll` optional does not look very strong in my opinion. Going bach from optional to required, however, will be a breaking change.

I'll leave this issue open for the time being and wait for more feedback and opinions.

**Comment by jcornaz** [comment]
I agree with @Sir4ur0n. 

As soon as one writes `@Property` the intent is clearly to write a property holding for all input. The `@ForAll` is only boilerplate. And I think avoiding the need for boilerplate is always good.

**Comment by t1** [comment]
I actually like the `@ForAll`, as it makes reading more fluent......... except for maybe `@Every` would be even better, as the property only tests one instance at a time ;-) i.e.:
```@Property should_be_divisible_by_two(@Every @Even @Positive Integer i)```

**Comment by jlink** [comment]
If you prefer @Every over @ForAll you can define that  annotation and use it. The mechanics to do that are described here: https://jqwik.net/docs/current/user-guide.html#self-made-annotations

**Comment by t1** [comment]
I tried
```
@Target({ANNOTATION_TYPE, PARAMETER})
@Retention(RUNTIME)
@Documented
@ForAll
public @interface Every {
    String NO_VALUE = "";

    String value() default NO_VALUE;
}
```

but I get a `JqwikException: All parameters must have @ForAll annotation`.

**Comment by jlink** [comment]
Looks like a bug at first glance. I'll have a look at it.

**Comment by jlink** [comment]
@t1 It was a bug indeed. Using 1.2.1-SNAPSHOT from https://oss.sonatype.org/content/repositories/snapshots will now allow you to user `@Every` instead of `@ForAll`. What does not work are annotation parameters, though. Thus, `@Every("strangeThing")` will NOT use the generator from method `strangeThing`. If you need that please open a new issue in order to discuss it.

**Comment by jlink** [comment]
Since lifecycle hooks (https://github.com/jlink/jqwik/issues/61) are eventually coming to jqwik I'm working on parameter injection. `@ForAll` will now be necessary to differentiate between injectable and non injectable parameters.

Therefore I've decided to keep `@ForAll` mandatory for parameters that are supposed to be randomly generated.
