### ISSUE TITLE
[Question] .jqwik-database Lifecycle Management

### ISSUE THREAD

**Issue by jburwell** [jlink/jqwik#69]
What is the guidance for deleting jqwik-database?  Is it advised to delete as part of the Maven clean lifecycle?

**Comment by jlink** [comment]
In theory you never have to delete it, it should be robust enough to recover from potential error scenarios. That said, you can create different behaviour by (not) deleting it: If you delete it during Maven clean jqwik will create new random seeds for failed properties. That means that after a property fails you cannot be sure it will fail in the next run since the generated sample data will most probably be different. If you only use `mvn clean` in CI runs this might be an option.

I personally never delete it - except when I work on a feature related to it. Have you had any problems that you think are related to an old .jqwik-database?

**Comment by jlink** [comment]
@jburwell Feel free to reopen if anything comes up

**Comment by jburwell** [comment]
> In theory you never have to delete it, it should be robust enough to recover from potential error scenarios. That said, you can create different behaviour by (not) deleting it: If you delete it during Maven clean jqwik will create new random seeds for failed properties. That means that after a property fails you cannot be sure it will fail in the next run since the generated sample data will most probably be different. If you only use `mvn clean` in CI runs this might be an option.
> 
> I personally never delete it - except when I work on a feature related to it. Have you had any problems that you think are related to an old .jqwik-database?

Yes.  When we upgraded from 0.9.x to 1.1.6, our test suite mysteriously failed.  Deleting `jqwik-database` and re-executing the test suite fixed the problem.  This solution caused me wonder how it is intended to be managed,  Currently, we ignore it from source control.  Do you check it in?

**Comment by jlink** [comment]
Checking it in doesn’t make sense IMO since it will be recreated on each test run. 

If you run into a migration problem again I’d be interested in the details.

**Comment by gerardoepitacio** [comment]
@jlink I think my question is related to this topic, since you mention that `"it will be recreated on each test run"`, it's safe to set this file in the .gitignore file to avoid track it with git?

**Comment by jlink** [comment]
At least that’s what I do. If you put it into VC on failing tests, you’ll *sometimes* be able to create the same failing values where you checkout the code. But that’s rarely what you want.
