### ISSUE TITLE
Checking an invariant should return a check result instead of throwing an exception

### ISSUE THREAD

**Issue by gtrefs** [jlink/jqwik#71]
The `check` of an `Invariant` fails when an `Exception` is thrown:

```Java
Invariant<String> invariant = s -> throw new RuntimeException("I don't like strings");
invariant.check(); // Runtime exception indicates that the invariant does not hold 
```

IMO, it would make more sense to return a `CheckResult`. In case the invariant does not hold, it can be `CheckFailure` and otherwise `CheckSuccess`. This makes it easier to work with the API and one knows how to indicate failures. For example:

```Java
Invariant<String> invariant = string -> CheckResult.failure("I don't like strings");
var result = invariant.check();
assertThat(result).isInstanceOf(CheckFailure.class);
var message = invariant.asFailure().getMessage();
assertThat(message).isEqualTo("I don't like strings"); 
```

**Comment by jlink** [comment]
The idea is that you use the same assertions (or assertion library) in your invariant as you use in other checks. Your example would look like

`Invariant<String> invariant = s -> Assertions.fail("I don't like strings");
`

Since the invariant should never be checked explicitly -- but is used internally for model/state based sequence checking -- I don't see how introducing `CheckResult` would simplify API usage. Maybe you can elborate? My guess is you want to use `Invariant` for something it has not been conceived to handle.

**Comment by gtrefs** [comment]
Thanks for the explanation.
