### ISSUE TITLE
Regression in jqwik 1.2.3

### ISSUE THREAD

**Issue by Serranya** [jlink/jqwik#88]
It seems that the values generated by `Arbitraries.strings().ofMinLength(2).unique()` are in fact not uniqe.

The follwing test fails with jqwik 1.2.3. It runs fine with jqwik 1.2.0 and 1.2.1.
https://github.com/condorcat/de.serra.condorcat/blob/b079ff35a71e301a8f267009d04656b08d94e9a1/src/test/java/de/serra/condorcat/model/InMemoryBallotStorePropertiesTest.java#L29-L37

Debugging revealed that indeed twice the same String was passed as id.

**Comment by Serranya** [comment]
https://github.com/jlink/jqwik/commit/6099e9595843eaf432dd3087cfa958d0b2067481 seems somewhat conspicuous. Both duplicated strings are `\u0000`

**Comment by jlink** [comment]
I'll have a detailed look tomorrow. 

As for your generator I'm wondering if
`var ids = Arbitraries.strings().ofMinLength(2).unique();` 
should get an additional constraint to only allow valid id characters. Is `\u0000` possible in IDs?

**Comment by Serranya** [comment]
Right now any String is valid as an ID. It just has to be unique. Later on I might need to constraint the Arbitrary a bit.

**Comment by jlink** [comment]
I think I figured it out. The problem is tricky in so far that https://github.com/jlink/jqwik/commit/6099e9595843eaf432dd3087cfa958d0b2067481 really did lead to the change in behaviour but it only raised the probability of it happening. It could (theoretically) have happened before. Let me explain...

Using any kind of combinator will create a new generator for each time it is invoked. That's why your use of `ids` is only unique within a single generated instance of `BallotStore.Entry`. That did not bite you up to 1.2.2 because the chances of duplicate characters were rather low - until I introduced edge cases for characters in 1.2.3. Edge cases have a higher chance of being generated.

Obviously what you want is unique IDs across all instances of `BallotStore.Entry`. To make sure that the same generator will be used you have to `map` or `flatMap` over it. So here is my suggestion to change your provider method:

```java
@Provide
Arbitrary<List<BallotStore.Entry>> uniqueEntries() {
	var ids = Arbitraries.strings().ofMinLength(2).unique();
	var titles = Arbitraries.strings();
	var owners = Arbitraries.strings();
	var choices = Arbitraries.strings().unique().array(String[].class);

	return ids.flatMap(id -> Combinators.combine(titles, owners, choices)
			.as((title, owner, choice) -> {
				BallotStore.Entry entry = new BallotStore.Entry();
				entry.id = id;
				entry.title = title;
				entry.owner = owner;
				entry.choices = choice;
				return entry;
			})).list();
}
```

I also changed to a different combinator's syntax because it seemed simpler here.

Does that suit your need?

**Comment by jlink** [comment]
BTW, one might think that generators should be shared across all usages of an arbitrary within one property. But that would lead to all kind of other strange and non intuitive behaviour.

I have a feature in the backlog to allow explicit sharing of generators but it does not have high priority - unless someone convinces me that it should.

**Comment by Serranya** [comment]
@jlink thanks for the detailed and fast explanation. Your suggestion should solve my problem.

I really appreciate your work on jqwik :)

**Comment by ThibautGeriz** [comment]
> I have a feature in the backlog to allow explicit sharing of generators but it does not have high priority - unless someone convinces me that it should.

@jlink Not sure it will convince you but I run in the same issue.

**Comment by jlink** [comment]
@ThibautGeriz Did you run into the "unique" issue or in sharing generators of some other kind? I'm asking because jqwik's approach to uniqueness will change in 1.4.0. See: https://jqwik.net/docs/snapshot/user-guide.html#uniqueness-constraints

**Comment by ThibautGeriz** [comment]
Hum I am not sure I understand the question, I was using the [builder](https://jqwik.net/docs/snapshot/user-guide.html#combining-arbitraries-with-builder) with one property with a `.unique()` method and it was not working. 
I switched to the flatMap with the Combinator and it worked just fine. Not what it implies behind the hood.

The new uniqueness constraint looks like to it would apply to list, meaning I would have to impl the equal of my object. In my case, I want the id of my object to be unique not the whole object.

On a side note, I would leave that issue open to document this known bug (with its work around).

**Comment by jlink** [comment]
> The new uniqueness constraint looks like to it would apply to list, meaning I would have to impl the equal of my object.

Actually you can use `uniqueElements(o -> o.getId())` to just ensure unique IDs.
